# Generated by Django 5.0 on 2025-11-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for this product', null=True),
        ),
    ]
