# Generated by Django 5.0 on 2025-11-19 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward_admin', '0002_product_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dashboard_banner/')),
                ('title', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'e_com_dashboard_banner',
            },
        ),
        migrations.CreateModel(
            name='dashboard_banner_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dashboard_banner_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reward_admin.dashboard_banner')),
            ],
            options={
                'db_table': 'e_com_dashboard_banner_image',
            },
        ),
    ]
