# Generated by Django 5.0 on 2025-11-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward_admin', '0003_dashboard_banner_dashboard_banner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dashboard_banner_image',
        ),
    ]
