"""
Django settings for reward project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%c_edfhas+)*s2u6c0it-9+1qibinqr1f5zvp-**81dnl(q4fv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'widget_tweaks',
    'rest_framework.authtoken',
    'reward_admin',
    'sass_processor',  # For processing SASS files
    'corsheaders',  # For handling CORS
    'rest_framework_simplejwt.token_blacklist',  # For token blacklisting
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'reward.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'reward_admin.context_processor.system_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'reward.wsgi.application'

AUTH_USER_MODEL = 'reward_admin.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'reward_admin.auth_backends.MembershipIDBackend',
]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecom',  # Name of your database
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',  # Set charset to utf8mb4 to support emojis
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }
    }
}
# ### A2Hosting ####
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'redsahos_presidencyclubs',
#         'USER': 'redsahos_presidencyclubs',
#         'PASSWORD': 'presidencyclubs',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {
#             'charset': 'utf8mb4',  # Set charset to utf8mb4 to support emojis
#         },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS=[
    BASE_DIR /'static',  # static files in the project root
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_DOMAIN = 'https://presidencyclubs.reds.a2hosted.com/media/'  # ✅ Add this line if not already present
STATIC_DOMAIN = 'https://presidencyclubs.reds.a2hosted.com/static/'  # ✅ Add this line if not already present
DOMAIN = 'https://presidencyclubs.reds.a2hosted.com'  # ✅ Add this line if not already present

LOGIN_URL = 'adminlogin'  # Using the URL name instead of path

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Use JWT for authentication
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',  # Important for file uploads
        'rest_framework.parsers.FormParser',
    ),
    'EXCEPTION_HANDLER': 'reward_api.utils.exceptions.custom_exception_handler',  # Add this line
}

# JWT Configuration
SIMPLE_JWT = {
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=160),  # Token validity period
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),  # Refresh token validity period
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,     
    'AUTH_HEADER_TYPES': ('Bearer',),  # Use Bearer tokens for authorization
}

# Email Configuration (Gmail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'presidencyclubs.reds.a2hosted.com'  # A2 Hosting SMTP server
EMAIL_PORT = 465  # Standard SSL port
EMAIL_USE_TLS = False  # Disable TLS (since SSL is used)
EMAIL_USE_SSL = True  # Enable SSL (required for port 465)
EMAIL_HOST_USER = 'presidencyclub@presidencyclubs.reds.a2hosted.com'  # Your A2 Hosting email
EMAIL_HOST_PASSWORD = 'Redspark@1'  # Your email password
DEFAULT_FROM_EMAIL = 'presidencyclub@presidencyclubs.reds.a2hosted.com'  # Same as EMAIL_HOST_USER

